### ISSUE TITLE
I2C reads on i2c-p2 and i2c-p3 hang (but writes work great)

### ISSUE THREAD

**Issue by jaydcarlson** [OpenNuvoton/NUC980-linux-4.4.y#1]
I'm trying to communicate with some I2C devices attached to I2C2, using PB5 as SCL and PB7 as SDA. I have a simple temperature sensor with an address of 0x18 attached to the bus.

If I write to the device:
```
i2cset -y 2 0x18 0x00 0x00
```
I get no problems:
![image](https://user-images.githubusercontent.com/4217991/62330335-fc668680-b47d-11e9-9d64-2716b56552dc.png)

But if I read from the device:
```
i2cget -y 2 0x18 0x00
```
The bus hangs:
![image](https://user-images.githubusercontent.com/4217991/62330387-26b84400-b47e-11e9-8495-b3d37a9dd518.png)

Not shown in the above timescale, but SDA times out after ~25ms and returns high. SCL never gets released, though.

This hangs the entire kernel, and I have to perform a hardware reset.

I've tested this on multiple I2C slave devices, and originally discovered the problem after noticing my kernel modules for the InvenSense MPU-6050 and Analog Devices AD5933 were both hanging when I attempt reads.

I switched to I2C3, but it has the same problem.

This is on a freshly-built kernel using Nuvoton's provided Buildroot environment:
```
# uname -a
Linux buildroot 4.4.179 #19 PREEMPT Thu Aug 1 17:06:36 CDT 2019 armv5tejl GNU/Linux
```

Any ideas?

**Comment by yachen** [comment]
Hi,

Please pull  0ee9bda   and test again. Thanks.


Sincerely,

Yi-An Chen

**Comment by jaydcarlson** [comment]
Thanks! Works a treat!
