### ISSUE TITLE
如何设置内核从SPI NAND启动

### ISSUE THREAD

**Issue by M16AK47MMM** [OpenNuvoton/NUC980-linux-4.4.y#100]
按照官方Linux-4.4_BSP设置SPI NAND，但每次上电依然检测SPI norFlash，没有识别SPI NAND W25N01GV型号，请问在配置内核时有哪些细节需要注意？
![03](https://user-images.githubusercontent.com/106132460/170439375-069fc7a0-3288-421f-a4a5-7a133fceb3a3.png)

**Comment by cwweng-nuvoton** [comment]
請打開 Device Drivers -> Staging drivers -> SPINAND Device Support
![image](https://user-images.githubusercontent.com/47778290/170475251-aa88aec1-0dba-47d9-a501-58760592a8b1.png)

**Comment by M16AK47MMM** [comment]
Staging drivers配置我全部打开了的，但依然无法识别SPI NAND W25N01GV型号
![04](https://user-images.githubusercontent.com/106132460/170476975-dcf0aada-f296-42f9-b009-f4761b264f02.png)
![Uploading 05.png…]()

**Comment by M16AK47MMM** [comment]
![05](https://user-images.githubusercontent.com/106132460/170477849-1555c8f8-04ba-4093-a096-41b8782f4d6f.png)

**Comment by cwweng-nuvoton** [comment]
請提供你的 kernel config

**Comment by M16AK47MMM** [comment]
[config.txt](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/files/8785051/config.txt)

**Comment by M16AK47MMM** [comment]
按照正常的Linux内核图形界面配置，在启动时仍无法识别到SPI NANDFlash，是否需要对源代码进行修改。

**Comment by cwweng-nuvoton** [comment]
arch/arm/mach-nuc980/dev.c 當中定義 使用 SPI NOR 或 SPI NAND  驅動
![image](https://user-images.githubusercontent.com/47778290/170662574-b03b1d82-ba5e-413b-8ab7-e8f1f638d46c.png)
如果有定義 CONFIG_BOARD_IOT, CONFIG_BOARD_ETH2UART, CONFIG_BOARD_LORA 當中一個, 就會啟動 SPI NAND 驅動

你的 config 都沒有定義 CONFIG_BOARD_IOT, CONFIG_BOARD_ETH2UART, CONFIG_BOARD_LORA  當中的任何一個
![image](https://user-images.githubusercontent.com/47778290/170663709-954111d7-61b7-43c0-8d27-702f95dd3b26.png)
所以就會啟動 SPI NOR 驅動,  而非 SPI NAND  驅動
