### ISSUE TITLE
NUC980-linux-4.4.289内核版本是否存在网络连接热插拔检测？

### ISSUE THREAD

**Issue by M16AK47MMM** [OpenNuvoton/NUC980-linux-4.4.y#103]
更新到4.4.289版本最新内核，调试发现在重启或者上电复位后，如果不插拔网线，则网络断开无法连接；在图形界面立是否有选项支持网线不用热插拔也能正常连接通讯的需求？

**Comment by M16AK47MMM** [comment]
![ip](https://user-images.githubusercontent.com/106132460/171364812-dbc6ea5c-fac1-49f2-8c08-12df54a0ec85.png)

**Comment by yclu-ntc** [comment]
我上電復位後使用udhcpc取得ip位址並與router通訊，RX/TX封包都正常，PC端ping也是ok的，並不需要重新插拔網線，可能需要您描述環境與下了那些命令
![nuc980net](https://user-images.githubusercontent.com/108246748/175851297-46de3a63-1f75-414d-bf7b-d91e2efbd295.PNG)
