### ISSUE TITLE
Question: Online webpage update firmware

### ISSUE THREAD

**Issue by webrtcccccc** [OpenNuvoton/NUC980-linux-4.4.y#119]
Dear Sir,

Is there a way to update the firmware using the webpage? Similar to the OTA function.

**Comment by enginlee** [comment]
It's not related to Linux kernel or BSP. There are many ways to do it depend on your requirement/condition.
For standard method, you can refer to OpenWRT. Official port can be found here: [https://github.com/OpenNuvoton/NUC980-OpenWrt](url)

**Comment by webrtcccccc** [comment]
Thank you, I also found another relevant documentation, I will test these methods again.
https://www.nuvoton.com/export/resource-files/AN_0062_OTA_Update_on_U-Boot_EN_Rev1.00.pdf
