### ISSUE TITLE
NUC980 UID

### ISSUE THREAD

**Issue by ct991218620** [OpenNuvoton/NUC980-linux-4.4.y#120]
请教下这个芯片UID读取是0，是不支持UID吗？

**Comment by ychuang3** [comment]
是的，沒有 UID
因為 NUC980 沒有可以記錄 UID 的實體裝置 (OTP, MTP, ROM, Flash, etc.)

**Comment by ct991218620** [comment]
> 是的，沒有 UID 因為 NUC980 沒有可以記錄 UID 的實體裝置 (OTP, MTP, ROM, Flash, etc.)

好的谢谢，我想通过UID给以太网生成唯一MAC，我已经找到了另外一个方法了，感谢。
