### ISSUE TITLE
Undeclared udc if CONFIG_PM is defined

### ISSUE THREAD

**Issue by yewhon** [OpenNuvoton/NUC980-linux-4.4.y#130]
In file /drivers/usb/gadget/udc/nuc980_udc.c, if `CONFIG_PM` is defined, 
1. [line 1689](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/blob/86ccd79cca3c2deb4f1aef71951d943f7ca3ba12/drivers/usb/gadget/udc/nuc980_udc.c#L1689) in function `nuc980_udc_suspend` has undeclared `udc`.
2. [line 1695](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/blob/86ccd79cca3c2deb4f1aef71951d943f7ca3ba12/drivers/usb/gadget/udc/nuc980_udc.c#L1695C2-L1695C2) in function `nuc980_udc_resume` has undeclared `udc`.

Suggestion:
1. Maybe adding `struct nuc980_udc *udc = platform_get_drvdata (pdev);` to the beginning of both functions is the solution?

**Comment by ychuang3** [comment]
We fixed it in the latest commit. Thanks.
