### ISSUE TITLE
jffs2 Newly-erased block contained word问题

### ISSUE THREAD

**Issue by QHxiedong** [OpenNuvoton/NUC980-linux-4.4.y#134]
产品Flash是SPI NOR Flash W25Q256，出现了jffs2 Newly-erased block contained word，如下图所示，请帮忙指导如何查找和解决问题，谢谢！

![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/1d063397-20d4-435f-83c4-acbadeac35d6)

**Comment by cwweng-nuvoton** [comment]
請問是在 W25Q256 SPI Flash 上 mount JFFS2 root file system 時出現這個錯誤嗎 ?
還是做什麼操作出現的 ?

**Comment by QHxiedong** [comment]
mount时还没有出现，在写文件时会出现，读文件时没有出现。

例如下图拷贝log.txt到log.txt1会出现
![0f418810b06a4a50016c584b5025c092](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/2e78ffd6-141e-49a1-a9a2-a3cb78dce9c9)
但是单板复位再启动，log.txt1并没有被保存下来。如下图：
![792c04ffa32ff160f79d3ce096dffe83](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/2f006eda-cf82-40a5-abbd-1745a2b97226)

**Comment by cwweng-nuvoton** [comment]
我仿造你做同樣的拷貝文件,  但是沒有出現你說的錯誤
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/47778290/e58cb25f-d0db-4f0e-9b07-1e9e6360bcc5)
板子復位後, log.txt1 也有保存下來

你的內核是最新的嗎 ?  
有沒有做什麼修改 ?

**Comment by QHxiedong** [comment]
内核版本是：4.4.289
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/d01bdcc0-3837-46c7-b0e3-17f9b71d31a4)

不是每台设备都是这样的，生产了900台设备，目前发现只有2台设备出现了这样的问题，剩余的设备都暂时正常工作中。

**Comment by QHxiedong** [comment]
最早的设备是22年4月份开始上线运行的

**Comment by cwweng-nuvoton** [comment]
請檢查一下 W25Q256 的 Status Register-1 的 Block protect 是否被設起來了
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/47778290/ea59ec2c-4ae5-4cd9-b23a-332e3f1758ee)
如果 Block protect 設起來,  erase/write 會出現錯誤

**Comment by QHxiedong** [comment]
我代码里添加了这行打印：
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/581607d3-8dc7-4aa1-8a67-db15a1a7dea6)
运行打印都是0x0，如下：
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/c3b47f96-c740-45a1-8e0d-211a3fe05852)

我添加的代码是否存在错误？

**Comment by QHxiedong** [comment]
我增加了读取SPINOR_OP_RDCR这个寄存器，貌似Status Register-2的CMP位被置位成1了，整个芯片被protect了？

![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/f9bd0a13-bb6c-44f1-a2db-8bbb3020e976)
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/335aad7e-3eae-469a-b0b9-34e0e52d0413)
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/cbd7935d-968e-47b5-8e9d-685d8cfb702c)
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/535591d0-e775-4ed8-8497-cab8fdcb2ab2)

**Comment by cwweng-nuvoton** [comment]
對.  整個 W25Q256 都被 erase/write protect 了

**Comment by QHxiedong** [comment]
1. 导致整个W25Q256被 erase/write protect原因可能是什么呢？
2. 我应该如何解除erase/write protect，能否在应用层解决？

谢谢！

**Comment by cwweng-nuvoton** [comment]
同樣在 read_sr() 裡面,  用  nor->write_reg() 將 Status Register-2 的 CMP bit 清為 0
試試看

**Comment by QHxiedong** [comment]
通过清除CMP，可以恢复正常了，设置sqlite数据库数据和新建文件夹均正常，重启后文件均保存了。
重启前：
![2ab64a76df9d8f6f6b430f1db6d2f105](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/266692af-8f72-4460-894e-9e820f81afb8)
重启后：
![ddf090aaf852cc9cdc6d8da182130336](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/d165edd7-73f1-469e-9d15-969201925374)

请问能否在应用层更改CMP的值，可以的话，请帮忙提供下方法。
如果只能在驱动层更改，针对这个问题，最合理的解决方案是什么？
谢谢！

**Comment by cwweng-nuvoton** [comment]
在應用層運行 spidev_test,  通過參數 -p 傳送 0x31 command 將 W25Q256 的 status-2 寄存器的 CMP bit 清為 0
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/47778290/3281c873-1e1e-4bee-be1f-02897a172b71)

另外, 要記得修改 arch/arm/mach-nuc980/dev.c, 將 QSPI0 原本的  m25p80 註解掉, 改為
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/47778290/74476385-b1a6-46fc-85dd-78ff7b79dc70)
就可以把 W25Q256 當成一般的 SPIDEV 存取

**Comment by QHxiedong** [comment]
这个方法也要改内核代码，考虑到设备也都发货到客户手中了，还是选择从驱动代码里面修改。

我写了个CMP位检查并清零的函数，在spi_nor_scan函数中调用，如下所示：

函数：
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/508b5293-49fc-460b-98aa-eb688383d342)

调用：
![image](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/assets/84755077/60882012-e776-4cdf-8963-e17dcf79cb50)

经过验证是可以的，不知道是否合理，请帮忙指导下，谢谢！

**Comment by cwweng-nuvoton** [comment]
客戶會有 erase/write protect 的需求嗎 ?
如果沒有, 這樣的修改 OK.
這樣修改後, 每次啟動都會將 W25Q256 status-2 寄存器的 CMP bit 清為 0

**Comment by QHxiedong** [comment]
是的，每次启动都会将CMP清零。客户没有erase/write保护的需求。
现在的方式需要等到重启设备才能解决，请问有更好的方法吗，出现问题时能实时解决掉。
通过dmesg打印的“Node totlen on flash”可以定位到jffs2_mark_node_obsolete函数， “Newly-erased block contained word”定位到jffs2_block_check_erase函数。但是我不知道应该调用什么函数可以将W25Q256的SR_2寄存器的CMP位清零。
