### ISSUE TITLE
anti reverse engineering?

### ISSUE THREAD

**Issue by AnterCreeper** [OpenNuvoton/NUC980-linux-4.4.y#135]
1. How to read the things like unique IDs or serial numbers? and AFAIK NUC980 doesn't have eFuse(OTP)?
2. Any way to achieve Trusted boot?

**Comment by ychuang3** [comment]
The NUC980 does not have OTP or any storage device to record UID (Unique Identifier), and it also does not support secure/trust boot.
You may consider choosing either NUC970 or MA35D1 instead.
