### ISSUE TITLE
Does 64pin NUC980 support SPI-NAND

### ISSUE THREAD

**Issue by AnterCreeper** [OpenNuvoton/NUC980-linux-4.4.y#136]
from Datasheet and Hardware Design Guide, I see pin PG[9:8], normally not be fanned out and pull up internally, meaning that only SPI Nor Flash, isn't it?

**Comment by ychuang3** [comment]
The following chip type supports SPI NOR only:
NUC980DR61YC
NUc980DR61
NUC980DR41YC
NUC980DR41

**Comment by AnterCreeper** [comment]
what about DR63? What settings do I need to apply?

**Comment by AnterCreeper** [comment]
It seems that 3 is a new stepping above 1. Emmm, my datasheet is pretty old...

**Comment by ychuang3** [comment]
DR63 is the same as DR61, but with different DRAM (internal) version.
Anyway, 64 pins package (NUC980xxDRxx series) does not support SPI NAND.

**Comment by AnterCreeper** [comment]
thanks a lot
