### ISSUE TITLE
发现I2C Read问题，并提供修改方案

### ISSUE THREAD

**Issue by zyj9527** [OpenNuvoton/NUC980-linux-4.4.y#14]
i2c驱动中iicstat == M_RECE_ADDR_ACK后，没有使能ACK，导致read第一个byte数据后，master没有发ACK，按照如下修改就OK了：
![image](https://user-images.githubusercontent.com/15027070/67909532-8b3c8980-fbba-11e9-8e43-0ad5a1676934.png)

**Comment by yachen** [comment]
Hi, Would you like to send a pull request, or do you prefer I modify our tree directly?

**Comment by zyj9527** [comment]
Hi，you may modify your tree directly

**Comment by yachen** [comment]
Done. Thanks a lot.
