### ISSUE TITLE
NAND Flash not found during boot on NUC980ETH2UART board

### ISSUE THREAD

**Issue by NUC980ETH2UART** [OpenNuvoton/NUC980-linux-4.4.y#21]
EDIT: Readability.
I am using nuc980 bsp, and writing image from linux NuWriter. I am using nuc980_eth2uart_defconfigs to build rootfs, u-boot, and the kernel.
Chip is NUC980DK61YC
My .ini file for NuWriter

> image_num = 4
> image0_path= /home/notpi/WORKING_DIR/nuc980bsp/ZZZZZZ/u-boot-spl.bin
> image0_type = loader
> image0_exe_addr = 0x000200
> image0_start_offset = 0x00000
> 
> image1_type = data
> image1_path= /home/notpi/WORKING_DIR/nuc980bsp/ZZZZZZ/u-boot.bin
> image1_exe_addr = 0x0000
> image1_start_offset = 0x100000
> 
> image2_type = data
> image2_path= /home/notpi/WORKING_DIR/nuc980bsp/ZZZZZZ/980uimage
> image2_exe_addr = 0x0000
> image2_start_offset = 0x200000
> 
> image3_type = env
> image3_path= /home/notpi/WORKING_DIR/nuc980bsp/ZZZZZZ/env.txt
> image3_exe_addr = 0x00000
> image3_start_offset = 0x80000

My env.txt

> baudrate=115200
> bootcmd=run setspi;run loadkernel;bootm 0x7fc0
> bootdelay=1
> loadkernel=sf read 0x7fc0 0x200000 0x300000
> setspi=sf probe 0 40000000
> stderr=serial
> stdin=serial
> stdout=serial
> bootargs=noinitrd ubi.mtd=2 root=ubi0:system rw rootfstype=ubifs console=ttyS0,115200n8 rdinit=/sbin/init mem=64M mtdparts=nand0:0x200000@0x0(u-boot),0x1400000@0x200000(kernel),-(user) ignore_loglevel

NUC980's log after writing image

> NUC980 IBR 20180813
> Boot from USB
> DDR-OK
> \=======================================
> Run firmware code
> CPU: 300MHz, DDR: 300MHz, SYS: 300MHz, PCLK: 150MHz
> Parse NuWriter command line
> \=======================================
> SPI NOR ID=0x0000ffff  _spi_type =0
> SPI NOR ID=0x0000ffff  _spi_type =0
> 
> SPI NAND: Auto Detect
> ID=[0xefaa21]
> BlockPerFlash = 1024, PagePerBlock = 64
> PageSize = 2048, SpareArea = 64
> QuadReadCmd    = 0x6b
> ReadStatusCmd  = 0xff
> WriteStatusCmd = 0xff
> StatusValue    = 0xff
> Dummybyte      = 0x1
> 
> NAND ID=[f7][f7][f7][f7]
> PowerOn setting 0x7f6001d4
> BlockPerFlash=1023, PagePerBlock=64, PageSize=2048
> 
> eMMC1/SD1 eMMCBlockSize=0xffff0115(-65259)
> 
> Finish get INFO!!

U-boot log file

> NUC980 IBR 20180813
> Boot from SPI-NAND
> DDR-OK
> finish SPI dow▒c{
>                  #S
>  SPL load main U-Boot from SPI NAND Flash! (Jan 23 2020 13:48:45)
> initcall: 00e389d8
> 
> 
> U-Boot 2016.11-g60b7bee-dirty (Jan 23 2020 - 13:48:26 +0300)
> 
> initcall: 00e0c730
> U-Boot code: 00E00000 -> 00E50AA4  BSS: -> 00E5D1EC
> initcall: 00e00364
> CPU: NUC980
> initcall: 00e0ccc0
> Board: NUC980
> initcall: 00e0c75c
> DRAM:  initcall: 00e00d84
> initcall: 00e0ca50
> Monitor len: 0005D1EC
> Ram size: 04000000
> Ram top: 04000000
> initcall: 00e0c640
> initcall: 00e0c658
> initcall: 00e0c6e4
> Reserving 372k for U-Boot at: 03fa2000
> initcall: 00e0c6b8
> Reserving 1088k for malloc() at: 03e92000
> initcall: 00e0c8ec
> Reserving 88 Bytes for Board Info at: 03e91fa8
> initcall: 00e0c950
> initcall: 00e0c684
> Reserving 160 Bytes for Global Data at: 03e91f08
> initcall: 00e0c7b4
> initcall: 00e0c940
> initcall: 00e0cacc
> initcall: 00e0ca30
> initcall: 00e0c974
> 
> RAM Configuration:
> Bank #0: 0 64 MiB
> Bank #1: 0 0 Bytes
> 
> DRAM:  64 MiB
> initcall: 00e0c668
> New Stack Pointer is: 03e91ee0
> initcall: 00e0c8a8
> initcall: 00e0c83c
> Relocation Offset is: 031a2000
> Relocating to 03fa2000, new gd at 03e91f08, sp at 03e91ee0
> initcall: 03faeb18
> initcall: 03faeb20
> initcall: 00e0cc70 (relocated to 03faec70)
> initcall: 00e0cb38 (relocated to 03faeb38)
> initcall: 00e0cc88 (relocated to 03faec88)
> initcall: 00e0cc54 (relocated to 03faec54)
> using memory 0x3e92000-0x3fa2000 for malloc()
> initcall: 00e0cc90 (relocated to 03faec90)
> initcall: 00e0cb10 (relocated to 03faeb10)
> initcall: 00e0cc40 (relocated to 03faec40)
> initcall: 00e00e0c (relocated to 03fa2e0c)
> initcall: 00e11218 (relocated to 03fb3218)
> initcall: 00e0cc30 (relocated to 03faec30)
> initcall: 00e0cc14 (relocated to 03faec14)
> Now running in RAM - U-Boot at: 03fa2000
> initcall: 00e0cc80 (relocated to 03faec80)
> initcall: 00e0cbf8 (relocated to 03faebf8)
> NAND:  NAND Flash not found !
> NUC980 NAND CONTROLLER IS NOT SUPPORT THE PAGE SIZE. (0, 0)
> 0 MiB
> initcall: 00e0cbc8 (relocated to 03faebc8)
> SF: Got idcodes
> 00000000: ff ef aa 21 00                                     ...!.
> SF: Unsupported flash IDs: manuf ff, jedec efaa, ext_jedec 2100
> *** Warning - spi_flash_probe() failed, using default environment
> 
> Destroy Hash Table: 03fee1d0 table = 00000000
> Create Hash Table: N=67
> INSERT: table 03fee1d0, filled 1/67 rv 03ea29f8 ==> name="bootdelay" value="3"
> INSERT: table 03fee1d0, filled 2/67 rv 03ea2a0c ==> name="baudrate" value="115200"
> INSERT: free(data = 03e92618)
> INSERT: done
> initcall: 00e0cc9c (relocated to 03faec9c)
> initcall: 00e11234 (relocated to 03fb3234)
> initcall: 00e0cbb8 (relocated to 03faebb8)
> initcall: 00e0f094 (relocated to 03fb1094)
> In:    serial
> Out:   serial
> Err:   serial
> Initial value for argc=3
> Final value for argc=3
> Initial value for argc=3
> Final value for argc=3
> Initial value for argc=3
> Final value for argc=3
> initcall: 00e009cc (relocated to 03fa29cc)
> initcall: 00e0cba8 (relocated to 03faeba8)
> initcall: 00e0cb88 (relocated to 03faeb88)
> initcall: 00e00e3c (relocated to 03fa2e3c)
> initcall: 00e0cb6c (relocated to 03faeb6c)
> Net:   Net Initialization Skipped
> No ethernet found.
> initcall: 00e0cb60 (relocated to 03faeb60)
> \### main_loop entered: bootdelay=3
> 
>\### main_loop: bootcmd="\<UNDEFINED>"
> 

There are no reported mistakes in any steps beside booting.
Mistake might be by my side, and might be something basic. I've been trying to run this board for a week now.

**Comment by yachen** [comment]
Hi, Are you using latest U-Boot source code? Can't tell what goes wrong from the log you provided. We're on Chinese New Year vacation. Will check this issue after office open after vacation's over.

**Comment by NUC980ETH2UART** [comment]
I am using 
NUC970_U-Boot_v2016.11 which comes with nuc980 package. If there is one for nuc980 besides this, i couldn't find it. And enjoy your vacation.

**Comment by NUC980ETH2UART** [comment]
Progress. I used nuc980_iot_defconfig for u-boot, and it sees kernel image, and loads it. But, i can't get to the console yet.

Here is boot log,

> NUC980 IBR 20180813
> Boot from SPI-NAND
> DDR-OK
> finish SPI dow▒load
> 
>  SPL load main U-Boot from SPI NAND Flash! (Jan 28 2020 16:39:00)
> initcall: 00e3a354
> 
> 
> U-Boot 2016.11-g60b7bee-dirty (Jan 28 2020 - 16:38:42 +0300)
> 
> initcall: 00e0c7f8
> U-Boot code: 00E00000 -> 00E52614  BSS: -> 00E5F268
> initcall: 00e0036c
> CPU: NUC980
> initcall: 00e0cd8c
> Board: NUC980
> initcall: 00e0c824
> DRAM:  initcall: 00e00df0
> initcall: 00e0cb18
> Monitor len: 0005F268
> Ram size: 04000000
> Ram top: 04000000
> initcall: 00e0c6b0
> initcall: 00e0c7a0
> TLB table from 03ff0000 to 03ff4000
> initcall: 00e0c6c8
> initcall: 00e0c754
> Reserving 380k for U-Boot at: 03f90000
> initcall: 00e0c728
> Reserving 1152k for malloc() at: 03e70000
> initcall: 00e0c9b4
> Reserving 88 Bytes for Board Info at: 03e6ffa8
> initcall: 00e0ca18
> initcall: 00e0c6f4
> Reserving 168 Bytes for Global Data at: 03e6ff00
> initcall: 00e0c87c
> initcall: 00e0ca08
> initcall: 00e0cb94
> initcall: 00e0caf8
> initcall: 00e0ca3c
> 
> RAM Configuration:
> Bank #0: 0 64 MiB
> Bank # 1: 0 0 Bytes
> 
> DRAM:  64 MiB
> initcall: 00e0c6d8
> New Stack Pointer is: 03e6fee0
> initcall: 00e0c970
> initcall: 00e0c904
> Relocation Offset is: 03190000
> Relocating to 03f90000, new gd at 03e6ff00, sp at 03e6fee0
> initcall: 03f9cbe0
> initcall: 03f9cbe8
> initcall: 00e0cd3c (relocated to 03f9cd3c)
> initcall: 00e0cc00 (relocated to 03f9cc00)
> initcall: 00e0cd54 (relocated to 03f9cd54)
> initcall: 00e0cd20 (relocated to 03f9cd20)
> using memory 0x3e70000-0x3f90000 for malloc()
> initcall: 00e0cd5c (relocated to 03f9cd5c)
> initcall: 00e0cbd8 (relocated to 03f9cbd8)
> initcall: 00e0cd0c (relocated to 03f9cd0c)
> initcall: 00e00e6c (relocated to 03f90e6c)
> initcall: 00e11368 (relocated to 03fa1368)
> initcall: 00e0ccfc (relocated to 03f9ccfc)
> initcall: 00e0cce0 (relocated to 03f9cce0)
> Now running in RAM - U-Boot at: 03f90000
> initcall: 00e0cd4c (relocated to 03f9cd4c)
> initcall: 00e0ccc0 (relocated to 03f9ccc0)
> NAND:  NAND Flash not found !
> NUC980 NAND CONTROLLER IS NOT SUPPORT THE PAGE SIZE. (0, 0)
> 0 MiB
> SF: Got idcodes
> 00000000: ff ef aa 21 00                                     ...!.
> SF: Lock ops not supported for ef flash
> SF: Detected W25N01GV with page size 2 KiB, erase size 4 KiB, total 128 MiB
> initcall: 00e0cc90 (relocated to 03f9cc90)
> Destroy Hash Table: 03fddd40 table = 00000000
> Create Hash Table: N=512
> INSERT: table 03fddd40, filled 1/521 rv 03e967c8 ==> name="baudrate" value="115200"
> INSERT: table 03fddd40, filled 2/521 rv 03e96bec ==> name="bootcmd" value="run setspi;run loadkernel;bootm 0x7fc0"
> INSERT: table 03fddd40, filled 3/521 rv 03e97448 ==> name="bootdelay" value="1"
> INSERT: table 03fddd40, filled 4/521 rv 03e97308 ==> name="loadkernel" value="sf read 0x7fc0 0x200000 0x500000"
> INSERT: table 03fddd40, filled 5/521 rv 03e97aec ==> name="setspi" value="sf probe 0 50000000"
> INSERT: table 03fddd40, filled 6/521 rv 03e96f0c ==> name="stderr" value="serial"
> INSERT: table 03fddd40, filled 7/521 rv 03e96728 ==> name="stdin" value="serial"
> INSERT: table 03fddd40, filled 8/521 rv 03e97858 ==> name="stdout" value="serial"
> INSERT: free(data = 03e75b28)
> INSERT: done
> initcall: 00e0cd68 (relocated to 03f9cd68)
> initcall: 00e11384 (relocated to 03fa1384)
> initcall: 00e0cc80 (relocated to 03f9cc80)
> initcall: 00e0f1e4 (relocated to 03f9f1e4)
> In:    serial
> Out:   serial
> Err:   serial
> Initial value for argc=3
> Final value for argc=3
> Initial value for argc=3
> Final value for argc=3
> Initial value for argc=3
> Final value for argc=3
> initcall: 00e009d4 (relocated to 03f909d4)
> initcall: 00e0cc70 (relocated to 03f9cc70)
> initcall: 00e0cc50 (relocated to 03f9cc50)
> initcall: 00e00e9c (relocated to 03f90e9c)
> initcall: 00e0cc34 (relocated to 03f9cc34)
> Net:   Net Initialization Skipped
> No ethernet found.
> initcall: 00e0cc28 (relocated to 03f9cc28)
> /### main_loop entered: bootdelay=1
> 
> /### main_loop: bootcmd="run setspi;run loadkernel;bootm 0x7fc0"
> Hit any key to stop autoboot:  0
> SF: Got idcodes
> 00000000: ff ef aa 21 00                                     ...!.
> SF: Lock ops not supported for ef flash
> SF: Detected W25N01GV with page size 2 KiB, erase size 4 KiB, total 128 MiB
> device 0 offset 0x200000, size 0x500000
> SF: 5242880 bytes @ 0x200000 Read: OK
> /## Current stack ends at 0x03e6fcf0 *  kernel: cmdline image address = 0x00007fc0
> /## Booting kernel from Legacy Image at 00007fc0 ...
>    Image Name:   Linux-4.4.207+
>    Image Type:   ARM Linux Kernel Image (uncompressed)
>    Data Size:    4352736 Bytes = 4.2 MiB
>    Load Address: 00008000
>    Entry Point:  00008000
>    Verifying Checksum ... OK
>    kernel data at 0x00008000, len = 0x00426ae0 (4352736)
> /## No init Ramdisk
>    ramdisk start = 0x00000000, ramdisk end = 0x00000000
>    XIP Kernel Image ... OK
>    kernel loaded at 0x00008000, end = 0x0042eae0
> using: ATAGS
> /## Transferring control to Linux (at address 00008000)...
> 
> Starting kernel ...
> 
> SF: Got idcodes
> 00000000: ff ef aa 21 00                                     ...!.
> SF: Lock ops not supported for ef flash
> SF: Detected W25N01GV with page size 2 KiB, erase size 4 KiB, total 128 MiB
> SF: DeviceBooting Linux on physical CPU 0x0
> Linux version 4.4.207+ (root@notpi) (gcc version 7.4.0 (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) ) #5 PREEMPT Tue Jan 28 16:43:12 +03 2020
> CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=0005317f
> CPU: VIVT data cache, VIVT instruction cache
> Machine: NUC980
> Memory policy: Data cache writeback
> Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
> Kernel command line: root=/dev/ram0 console=ttyS0,115200n8 rdinit=/sbin/init mem=64M
> PID hash table entries: 256 (order: -2, 1024 bytes)
> Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
> Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
> Memory: 58188K/65536K available (3078K kernel code, 198K rwdata, 860K rodata, 2356K init, 199K bss, 7348K reserved, 0K cma-reserved)
> Virtual kernel memory layout:
>     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
>     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
>     vmalloc : 0xc4800000 - 0xff800000   ( 944 MB)
>     lowmem  : 0xc0000000 - 0xc4000000   (  64 MB)
>     modules : 0xbf000000 - 0xc0000000   (  16 MB)
>       .text : 0xc0008000 - 0xc03e0dcc   (3940 kB)
>       .init : 0xc03e1000 - 0xc062e000   (2356 kB)
>       .data : 0xc062e000 - 0xc065fb80   ( 199 kB)
>        .bss : 0xc065fb80 - 0xc0691abc   ( 200 kB)
> SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
> Preemptible hierarchical RCU implementation.
>         Build-time adjustment of leaf fanout to 32.
> NR_IRQS:545
> clocksource: nuc980-timer5: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 62215505635 ns
> sched_clock: 24 bits at 120kHz, resolution 8333ns, wraps every 69905062489ns
> Console: colour dummy device 80x30
> console [ttyS0] enabled
> Calibrating delay loop... 148.88 BogoMIPS (lpj=744448)
> pid_max: default: 32768 minimum: 301
> Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
> Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
> CPU: Testing write buffer coherency: ok
> Setting up static identity map for 0x8400 - 0x843c
> devtmpfs: initialized
> clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
> futex hash table entries: 256 (order: -1, 3072 bytes)
> pinctrl core: initialized pinctrl subsystem
> NET: Registered protocol family 16
> DMA: preallocated 256 KiB pool for atomic coherent allocations
> SCSI subsystem initialized
> usbcore: registered new interface driver usbfs
> usbcore: registered new interface driver hub
> usbcore: registered new device driver usb
> clocksource: Switched to clocksource nuc980-timer5
> NET: Registered protocol family 2
> TCP established hash table entries: 1024 (order: 0, 4096 bytes)
> TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
> TCP: Hash tables configured (established 1024 bind 1024)
> UDP hash table entries: 256 (order: 0, 4096 bytes)
> UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
> NET: Registered protocol family 1
> NetWinder Floating Point Emulator V0.97 (double precision)
> jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
> romfs: ROMFS MTD (C) 2007 Red Hat, Inc.
> Block layer SCSI generic (bsg) driver version 0.4 loaded (major 254)
> io scheduler noop registered (default)
> nuc980_gpio_probe - pdev = nuc980-gpio
> nuc980_dma_probe - pdev = nuc980-dma
> nuc980-dma nuc980-dma: NUC980 DMA ready
> nuc980-uart.0: ttyS0 at I/O 0x0 (irq = 36, base_baud = 750000) is a NUC980
> nuc980-uart.1: ttyS1 at I/O 0x0 (irq = 37, base_baud = 9375000) is a NUC980
> nuc980-uart.2: ttyS2 at I/O 0x0 (irq = 38, base_baud = 9375000) is a NUC980
> nuc980-uart.3: ttyS3 at I/O 0x0 (irq = 43, base_baud = 9375000) is a NUC980
> nuc980-uart.4: ttyS4 at I/O 0x0 (irq = 39, base_baud = 9375000) is a NUC980
> nuc980-uart.5: ttyS5 at I/O 0x0 (irq = 44, base_baud = 9375000) is a NUC980
> nuc980-uart.6: ttyS6 at I/O 0x0 (irq = 40, base_baud = 9375000) is a NUC980
> nuc980-uart.7: ttyS7 at I/O 0x0 (irq = 45, base_baud = 9375000) is a NUC980
> nuc980-uart.8: ttyS8 at I/O 0x0 (irq = 41, base_baud = 9375000) is a NUC980
> brd: module loaded
> m25p80 spi0.0: unrecognized JEDEC id bytes: ff, ef, aa
> RX nuc980_spi0_probe: dma0chan0 module removed
> TX nuc980_spi0_probe: dma0chan1 module removed
> m25p80 spi1.0: unrecognized JEDEC id bytes: ff, ff, ff
> m25p80: probe of spi1.0 failed with error -2
> libphy: nuc980_rmii0: probed
> libphy: nuc980_rmii1: probed
> ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
> nuc980-ehci nuc980-ehci: Nuvoton NUC980 EHCI Host Controller
> nuc980-ehci nuc980-ehci: new USB bus registered, assigned bus number 1
> nuc980-ehci nuc980-ehci: irq 23, io mem 0xb0015000
> nuc980-ehci nuc980-ehci: USB 2.0 started, EHCI 0.95
> hub 1-0:1.0: USB hub found
> hub 1-0:1.0: 2 ports detected
> ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
> usb_hcd_nuc980_probe, id = 0, name: nuc980-ohci.0, 0
> nuc980-ohci nuc980-ohci.0: Nuvoton NUC980 OHCI Host Controller
> nuc980-ohci nuc980-ohci.0: new USB bus registered, assigned bus number 2
> nuc980-ohci nuc980-ohci.0: irq 24, io mem 0xb0017000
> hub 2-0:1.0: USB hub found
> hub 2-0:1.0: 8 ports detected
> usb_hcd_nuc980_probe, id = 1, name: nuc980-ohci.1, 0
> usb_hcd_nuc980_probe, id = 2, name: nuc980-ohci.2, 0
> usb_hcd_nuc980_probe, id = 3, name: nuc980-ohci.3, 0
> usb_hcd_nuc980_probe, id = 4, name: nuc980-ohci.4, 0
> usb_hcd_nuc980_probe, id = 5, name: nuc980-ohci.5, 0
> usb_hcd_nuc980_probe, id = 6, name: nuc980-ohci.6, 0
> usbcore: registered new interface driver usb-storage
> usbcore: registered new interface driver usbhid
> usbhid: USB HID core driver
> NET: Registered protocol family 17
> Freeing unused kernel memory: 2356K
> nuc980-emac0 nuc980-emac0: eth0 is OPENED
> nuc980-emac1 nuc980-emac1: eth1 is OPENED
> random: nonblocking pool is initialized

Can you give me a working 980uimage, env.txt, u-boot.bin and u-boot-spl.bin for NUC980ETH2UART card so i can test if its actually working, or im doing something wrong.

And i don't know if it does matter but, product's box says NUC980DK61Y,
on the chip it says NUC980DK61YC. I checked ini files, they are same. I tried both anyway.

**Comment by NUC980ETH2UART** [comment]
I found something. nuc980_eth2uart_defconfig u-boot includes below settings which causes error for me;

> SF: Got idcodes
> 00000000: ff ef aa 21 00                                     ...!.
> SF: Unsupported flash IDs: manuf ff, jedec efaa, ext_jedec 2100
> SF: Lock ops not supported for ff flash
> SF: Detected <NULL> with page size 256 Bytes, erase size 0 Bytes, total 0 Bytes
> *** Warning - bad CRC, using default environment

-DeviceDriver->SPIFlashSupport->Winbond SPI flash support   ----> So i disable this option,
And i enable below option
-DeviceDriver->SPIFlashSupport->SPI NAND flash support->Select SPI NAND Flash (Winbond SPI NAND flash support)

This makes chip detected, linux loadable, and logs out this;
> SF: Got idcodes
> 00000000: ff ef aa 21 00                                     ...!.
> SF: Lock ops not supported for ef flash
> SF: Detected W25N01GV with page size 2 KiB, erase size 4 KiB, total 128 MiB
> initcall: 00e0cbc8 (relocated to 03facbc8)
> SF: Got idcodes
> 00000000: 00 ef aa 21 00                                     ...!.
> SF: Lock ops not supported for ef flash
> SF: Detected W25N01GV with page size 2 KiB, erase size 4 KiB, total 128 MiB
> *** Warning - bad CRC, using default environment

Is this supposed to happen? I discovered this while comparing iot and eth2p configs.
And boot takes around 5 minutes.

**Comment by yachen** [comment]
Hi,

Here's my step to execute image on ETH2UART board.
1. Load default ETH2UART U-Boot config.
2. make menuconfig->Device Drivers->SPI Flahs Support
2.1 Uncheck Winbond SPI flahs support
2.2 Check SPI NAND flash support.
2.3 Build U-Boot
3. Load default ETH2UART kernel config and build kernel.

We used to have SPI NOR on this board but replaced it with SPI NAND. I'll update the U-Boot config file for SPI NAND. Thanks.


Sincerely,

Yi-An Chen

**Comment by yachen** [comment]
By the way, please use nand commad to read data from SPI NAND instead of spi command.
nand read 0x7FC0 0x200000 <image length>
bootm 0x7fC0

**Comment by NUC980ETH2UART** [comment]
Thank you
