### ISSUE TITLE
USB host lite ports don't support hotplug detection

### ISSUE THREAD

**Issue by jaydcarlson** [OpenNuvoton/NUC980-linux-4.4.y#26]
It appears that USB devices must be attached to Host Lite ports on boot, and cannot be removed or replugged. 

If I have a USB device plugged into a host lite port on boot, it instantiates properly, but if I unplug it, Linux doesn't seem to become aware of that. If I don't have a device plugged in at boot, I'll get "unable to enumerate USB device" errors, and plugging a device in won't instantiate it without rebooting.

**Comment by yachen** [comment]
Hi, Which board are you working on?

**Comment by jaydcarlson** [comment]
Just a custom little break-out board I built for the 64-pin NUC980 package. And now that you mention it, I'm looking now and noticing the hardware design guide shows 15k pull-down resistors on the host lite ports. I assume I need those? lol that would explain it...

**Comment by jaydcarlson** [comment]
I added 15k pull-downs and that fixes the issue! Sorry for the bother!

**Comment by AnterCreeper** [comment]
> Just a custom little break-out board I built for the 64-pin NUC980 package. And now that you mention it, I'm looking now and noticing the hardware design guide shows 15k pull-down resistors on the host lite ports. I assume I need those? lol that would explain it...

Does NUC980 USB 1.1 FS Host Lite supported by 64pin product(DR63YC)?
From datasheet, it doesn't support(from PB_NUC980_Series_EN_1.0.pdf and TRM_NUC980_Series_EN_Rev1.01.pdf), but seems does support(from DS_NUC980_Series_EN_Rev1.24.pdf)......

**Comment by ychuang3** [comment]
NUC980 USB Host Lite is supported throughout the entire NUC980 series.
