### ISSUE TITLE
使用NK-980IOT开发板上的SPI1 (Port G) 在发送数据时（NU2插排PG11(SPI1_SS0)始终为高电平）  

### ISSUE THREAD

**Issue by ifdreams** [OpenNuvoton/NUC980-linux-4.4.y#28]

**Comment by ifdreams** [comment]
When using SPI1 (Port G) on the NK-980IOT development board to send data (NU2 socket PG11 (SPI1_SS0) is always high)

**Comment by ifdreams** [comment]
After SPI_CS_HIGH is selected (NU2 socket PG11 (SPI1_SS0) is always low

**Comment by yachen** [comment]
Hi, Please pull, it's fixed in 62cfd846e41777b5e37c28a262a9d70a56adff2f. Thanks.

**Comment by ifdreams** [comment]
good job!cheers!🍺
