### ISSUE TITLE
Error when canceling make menuconfig i2c selection

### ISSUE THREAD

**Issue by ifdreams** [OpenNuvoton/NUC980-linux-4.4.y#29]
make uImage

sound/soc/codecs/nau8822.c:1145:1: warning: data definition has no type or storage class [enabled by default]
 module_i2c_driver(nau8822_i2c_driver);
 ^
sound/soc/codecs/nau8822.c:1145:1: error: type defaults to ‘int’ in declaration of ‘module_i2c_driver’ [-Werror=implicit-int]
sound/soc/codecs/nau8822.c:1145:1: warning: parameter names (without types) in function declaration [enabled by default]
sound/soc/codecs/nau8822.c:1136:26: warning: ‘nau8822_i2c_driver’ defined but not used [-Wunused-variable]
 static struct i2c_driver nau8822_i2c_driver = {
                          ^
cc1: some warnings being treated as errors
make[3]: *** [sound/soc/codecs/nau8822.o] Error 1
make[2]: *** [sound/soc/codecs] Error 2
make[1]: *** [sound/soc] Error 2
make: *** [sound] Error 2

**Comment by yachen** [comment]
Should be some config issue. Please refer to the kernel confg nuc980_iot_defconfig. 8822 driver is enabled in this config.

**Comment by ifdreams** [comment]
thanks.
