### ISSUE TITLE
GPIOG15 unable to operate.

### ISSUE THREAD

**Issue by ifdreams** [OpenNuvoton/NUC980-linux-4.4.y#30]
echo 207 > /sys/class/gpio/export
Please Check GPIOG15's multi-function = 0x7
sh: write error: Invalid argument

**Comment by yachen** [comment]
It's occupied by JTAG (function 7). Need to restore to function 0 before you can export it.

**Comment by ifdreams** [comment]
How to restore to function 0？

**Comment by ifdreams** [comment]
> It's occupied by JTAG (function 7). Need to restore to function 0 before you can export it.


Can you tell me how to restore to function 0? I enabled SPI1-PORTG, but I did not use PG15, I need to operate PG15 in user space

**Comment by yachen** [comment]
Ues this to restore all MFP occupied by JTAG back to GPIO
`__raw_writel((__raw_readl(REG_MFP_GPG_H) & ~0xFFFFF000) ,REG_MFP_GPG_H); `

**Comment by ifdreams** [comment]
thank you.
