### ISSUE TITLE
nuc980 sd0  SD0_nCD  

### ISSUE THREAD

**Issue by redworlf007** [OpenNuvoton/NUC980-linux-4.4.y#31]
nuc980 sd0  

SD0 card detect input pin
SD0_nCD is at  PB.8 or  PC.12

how can i   Configure  use which  one ?

**Comment by yachen** [comment]
Hi,

Both have card detect function, and it's selected by sd0_pins[] structure defined in pinctrl-nuc980.c.
Currently PC.12 is selected as CD pin for SD0.

Sincerely,

Yi-An Chen

**Comment by redworlf007** [comment]
> Hi,
> 
> Both have card detect function, and it's selected by sd0_pins[] structure defined in pinctrl-nuc980.c.
> Currently PC.12 is selected as CD pin for SD0.
> 
> Sincerely,
> 
> Yi-An Chen

thinks  , i  get it.
