### ISSUE TITLE
gpio中断只触发一次

### ISSUE THREAD

**Issue by gdyshi** [OpenNuvoton/NUC980-linux-4.4.y#32]
不论是sysfs方式，还是自己写驱动的方式。gpio中断只在申请后触发一次，后续再不触发。
一、sysfs方式如下：
echo "2" > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio2/direction
echo "rising" > /sys/class/gpio/gpio2/edge
触发A2电平变化，然后 cat /proc/interrupts 查看中断次数。不论触发多少次，中断计数均为1
echo "2" > /sys/class/gpio/unexport后，继续上述过程，会再触发一次，但仅触发一次

二、自己写驱动代码为：
...
                elem->irq=gpio_to_irq(elem->pin);
                if(request_irq(elem->irq, __irq_handler,irq_flag,DEVNAME, elem)){
...
然后在__irq_handler加打印，也是只触发一次，后续不再触发；卸载驱动，再加载后又仅可触发一次

我内核未用设备树方式，猜想是gpio中断未复位？

**Comment by yachen** [comment]
我們剛剛有使用最新版依你的方式測試沒問題. 請問你用哪個版本測試? 這問題應在 b847400 之後修復.

**Comment by gdyshi** [comment]
最新版本已解决
