### ISSUE TITLE
NUC980  SPI NAND 启动问题。

### ISSUE THREAD

**Issue by redworlf007** [OpenNuvoton/NUC980-linux-4.4.y#35]
1、NUC980 从 SPI NAND启动，SD0位置上有SD NAND。
2、可以从usb启动，并且可以烧录系统，串口控制台输出正常。
3、烧录完系统，从spi nand启动后，串口控制台一直打印乱码。
4、按理说，能烧录成功，启动就不应该乱码，求助。
![1](https://user-images.githubusercontent.com/70580352/93891897-832f9000-fd1e-11ea-8054-42d2d38cf348.png)
![2](https://user-images.githubusercontent.com/70580352/93891907-8591ea00-fd1e-11ea-87a5-eeae05c92863.png)

**Comment by redworlf007** [comment]
SPL load main U-Boot from SPI NAND Flash 

感觉是这里执行失败。

**Comment by redworlf007** [comment]
![3](https://user-images.githubusercontent.com/70580352/93897538-c5f46680-fd24-11ea-92e3-fe1fc33927a9.png)
烧录成功

**Comment by yachen** [comment]
Hi,

你在哪一張板子上測試? IoT, LoraG...?

Sincerely,

Yi-An Chen

**Comment by redworlf007** [comment]
谢谢，我找到问题了，我把uboot的烧录地址不对。

**Comment by redworlf007** [comment]
> 你好
> 
> 你在哪一张板子上测试？物联网，LoraG ...？
> 
> 真诚的
> 
> 陈宜安

谢谢，我找到问题了，是我uboot烧录错地址了。
