### ISSUE TITLE
串口使用dma读数据，延时太长

### ISSUE THREAD

**Issue by styfstr** [OpenNuvoton/NUC980-linux-4.4.y#38]
我使用nuc980串口的dma功能（波特率为2000000（2M）），去定时请求子设备的数据，980串口发送数据可以很快被子设备相应（示波器抓到大约25us就可以返回数据，共5个字节），但用户空间需要等待60ms左右才可以读取到来自子设备的数据。
将dma关闭，发现1-3ms即可收到来自子设备的数据。
请问串口dma功能是不是存在问题？

**Comment by yachen** [comment]
PDMA 要在知道傳輸長度時,  效能較好. UART 不知道接收長度的情況下要等到 PDMA timeout 才會回傳.
若是封包都很小, 且 CPU 還有足夠小能接收, 需要即時反應的傳輸可以考慮使用 CPU 處理. 不然 PDMA 有自身的設定要做, 再加上等  timeout, 效能不會比較好.

**Comment by styfstr** [comment]
感谢您的回复！

现在使用PDMA，是因为用了4个串口通信，cpu占用太高。应用还在开发中，怕后边出现问题。
