### ISSUE TITLE
内核是否没启用设备树功能

### ISSUE THREAD

**Issue by qiubin2016** [OpenNuvoton/NUC980-linux-4.4.y#44]
开发板：NuMaker-IIoT-NUC980，pcb丝印型号：NK-980IOT V1.0
配置：make  nuc980_iot_defconfig
内核是否没启用设备树功能?  该如何启用？

**Comment by yachen** [comment]
這個config default 沒開. 要開的話 menuconfig->Boot options->[*] Flattened Device Tree support

**Comment by qiubin2016** [comment]
ok

**Comment by qiubin2016** [comment]
启用内核设备树功能，开发板开机无法挂载文件系统。开启方法：menuconfig->Boot options->[*] Flattened Device Tree support

开发板：NuMaker-IIoT-NUC980，pcb丝印型号：NK-980IOT V1.0
配置：make nuc980_iot_defconfig
设备树文件：arch/arm/boot/dts/nuc980-iot-v1.0.dtb
--------u-boot env--------:
baudrate=115200
bootargs=noinitrd root=/dev/mtdblock2 rootfstype=yaffs2 rootflags=inband-tags console=ttyS0,115200n8 rdinit=/sbin/init mem=64M
bootcmd=run setspi;run loadkernel;run loaddtb;run bootmcmd
bootdelay=1
bootmcmd=bootm 0x7fc0 - 0x1400000
ethact=emac
loaddtb=sf read 0x1400000 0xB00000 0x80000
loadkernel=sf read 0x7fc0 0x200000 0x800000
setspi=sf probe 0 50000000
stderr=serial
stdin=serial
stdout=serial
--------开发板启动报错日志---------：
Starting kernel ...

SF: Detected W25N01GV with page size 2 KiB, erase size 128 KiB, total 128 MiB
SF: Device[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.4.179 (qiub@ubuntu1604) (gcc version 4.8.4 (GCC) ) #18 PREEMPT Fri Nov 27 14:54:41 CST 2020
[    0.000000] CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=0005317f
[    0.000000] CPU: VIVT data cache, VIVT instruction cache
[    0.000000] Machine model: Nuvoton NUC980 IOT V1.0
[    0.000000] Memory policy: Data cache writeback
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
[    0.000000] Kernel command line: noinitrd root=/dev/mtdblock2 rootfstype=yaffs2 rootflags=inband-tags console=ttyS0,115200n8 rdinit=/sbin/init mem=64M
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Memory: 56488K/65536K available (5658K kernel code, 372K rwdata, 1812K rodata, 176K init, 258K bss, 9048K reserved, 0K cma-reserved)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0xc4800000 - 0xff800000   ( 944 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xc4000000   (  64 MB)
[    0.000000]     modules : 0xbf000000 - 0xc0000000   (  16 MB)
[    0.000000]       .text : 0xc0008000 - 0xc0753f9c   (7472 kB)
[    0.000000]       .init : 0xc0754000 - 0xc0780000   ( 176 kB)
[    0.000000]       .data : 0xc0780000 - 0xc07dd240   ( 373 kB)
[    0.000000]        .bss : 0xc07dd240 - 0xc081da94   ( 259 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] 	Build-time adjustment of leaf fanout to 32.
[    0.000000] NR_IRQS:545
[    0.000000] clocksource: nuc980-timer5: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 62215505635 ns
[    0.000033] sched_clock: 24 bits at 120kHz, resolution 8333ns, wraps every 69905062489ns
[    0.000724] Console: colour dummy device 80x30
[    0.187883] console [ttyS0] enabled
[    0.191416] Calibrating delay loop... 148.88 BogoMIPS (lpj=744448)
[    0.262783] pid_max: default: 32768 minimum: 301
[    0.267624] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.274308] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.283316] CPU: Testing write buffer coherency: ok
[    0.289233] Setting up static identity map for 0x8400 - 0x843c
[    0.299974] devtmpfs: initialized
[    0.341649] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.352316] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.358824] pinctrl core: initialized pinctrl subsystem
[    0.366199] NET: Registered protocol family 16
[    0.373541] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.386816] <DT> nuc980_dt_device_init +
[    0.434441] <DT> nuc980_dt_device_init -
[    0.441774] pinctrl-nuc980 apb:pinctrl@b0000000: initialized NUC980 pinctrl driver
[    0.808424] SCSI subsystem initialized
[    0.818433] usbcore: registered new interface driver usbfs
[    0.826683] usbcore: registered new interface driver hub
[    0.833399] usbcore: registered new device driver usb
[    0.843508] Advanced Linux Sound Architecture Driver Initialized.
[    0.861941] clocksource: Switched to clocksource nuc980-timer5
[    0.965516] NET: Registered protocol family 2
[    0.973441] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.980433] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.987258] TCP: Hash tables configured (established 1024 bind 1024)
[    0.994108] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.999974] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    1.007083] NET: Registered protocol family 1
[    1.012741] RPC: Registered named UNIX socket transport module.
[    1.018624] RPC: Registered udp transport module.
[    1.023508] RPC: Registered tcp transport module.
[    1.028166] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    1.036024] NetWinder Floating Point Emulator V0.97 (double precision)
[    1.194358] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    1.201758] io scheduler noop registered (default)
[    1.208491] nuc980_gpio_probe - pdev = b0004000.gpio
[    1.216266] nuc980_dma_probe - pdev = b0008000.dma
[    1.241466] nuc980-dma b0008000.dma: NUC980 DMA ready
[    1.870491] b0070000.serial: ttyS0 at I/O 0xf0070000 (irq = 36, base_baud = 750000) is a NUC980
[    1.883316] b0071000.serial: ttyS1 at I/O 0xf0071000 (irq = 37, base_baud = 9375000) is a NUC980
[    1.971558] brd: module loaded
[    1.980766] RX nuc980_qspi0_probe: dma0chan0 module removed
[    1.989033] TX nuc980_qspi0_probe: dma0chan1 module removed
[    1.999733] RX nuc980_spi0_probe: dma0chan2 module removed
[    2.006358] TX nuc980_spi0_probe: dma0chan3 module removed
[    2.015974] spidev spi1.0: buggy DT: spidev listed directly in DT
[    2.023099] ------------[ cut here ]------------
[    2.027758] WARNING: CPU: 0 PID: 1 at drivers/spi/spidev.c:719 spidev_probe+0x170/0x1b4()
[    2.036116] Modules linked in:
[    2.039149] CPU: 0 PID: 1 Comm: swapper Not tainted 4.4.179 #18
[    2.045233] Hardware name: Nuvoton NUC980 (Device Tree)
[    2.050416] Backtrace: 
[    2.053249] [<c0012e2c>] (dump_backtrace) from [<c0013018>] (show_stack+0x18/0x1c)
[    2.060774]  r6:c0243484 r5:c06e8594 r4:00000000 r3:00000000
[    2.066658] [<c0013000>] (show_stack) from [<c01a769c>] (dump_stack+0x20/0x28)
[    2.074091] [<c01a767c>] (dump_stack) from [<c001ef50>] (warn_slowpath_common+0x80/0xb8)
[    2.082283] [<c001eed0>] (warn_slowpath_common) from [<c001f02c>] (warn_slowpath_null+0x24/0x2c)
[    2.091008]  r8:00000000 r7:c07b9794 r6:c07b9784 r5:c3a6be00 r4:c3a6be00
[    2.097774] [<c001f008>] (warn_slowpath_null) from [<c0243484>] (spidev_probe+0x170/0x1b4)
[    2.106133] [<c0243314>] (spidev_probe) from [<c02409b4>] (spi_drv_probe+0x6c/0x78)
[    2.113824]  r8:00000000 r7:c07b9794 r6:c07b9784 r5:00000000 r4:c3a6be00
[    2.120499] [<c0240948>] (spi_drv_probe) from [<c0207fdc>] (really_probe+0x1ac/0x26c)
[    2.128341]  r6:00000000 r5:c080c790 r4:c3a6be00 r3:c0240948
[    2.133999] [<c0207e30>] (really_probe) from [<c0208284>] (__device_attach_driver+0xa4/0xa8)
[    2.142449]  r8:c080c76c r7:00000001 r6:c07b9794 r5:c383fc98 r4:c3a6be00 r3:00000007
[    2.150183] [<c02081e0>] (__device_attach_driver) from [<c02064c0>] (bus_for_each_drv+0x64/0x94)
[    2.158999]  r6:c383fc98 r5:c02081e0 r4:00000000 r3:00000000
[    2.164658] [<c020645c>] (bus_for_each_drv) from [<c0207dd4>] (__device_attach+0x94/0xd8)
[    2.172866]  r6:c3a6be00 r5:c3a6be34 r4:c3a6be00
[    2.177449] [<c0207d40>] (__device_attach) from [<c02083bc>] (device_initial_probe+0x14/0x18)
[    2.185999]  r7:c39e7000 r6:c3a6be00 r5:c07b923c r4:c3a6be08
[    2.191633] [<c02083a8>] (device_initial_probe) from [<c02074e4>] (bus_probe_device+0x8c/0x94)
[    2.200333] [<c0207458>] (bus_probe_device) from [<c0205674>] (device_add+0x3b4/0x548)
[    2.208274]  r6:00000000 r5:c3a6be00 r4:c3a6be08 r3:00000001
[    2.213949] [<c02052c0>] (device_add) from [<c0241328>] (spi_add_device+0x8c/0x134)
[    2.221549]  r10:000000fd r9:c3831c10 r8:00000000 r7:c3831c10 r6:00000000 r5:c39e7000
[    2.229383]  r4:c3a6be00
[    2.231949] [<c024129c>] (spi_add_device) from [<c0242cd8>] (spi_register_master+0x40c/0x6bc)
[    2.240499]  r7:00000000 r6:c3a6be00 r5:c3f706e0 r4:c39e7000
[    2.246216] [<c02428cc>] (spi_register_master) from [<c024454c>] (spi_bitbang_start+0xa4/0x128)
[    2.254941]  r9:00000000 r8:c39e7000 r7:c3831c10 r6:00000000 r5:c39e7210 r4:c39e7000
[    2.262758] [<c02444a8>] (spi_bitbang_start) from [<c0247068>] (nuc980_spi0_probe+0x68c/0x958)
[    2.271316]  r5:c3aaf0c0 r4:c39e7210
[    2.274958] [<c02469dc>] (nuc980_spi0_probe) from [<c0209994>] (platform_drv_probe+0x3c/0x74)
[    2.283516]  r8:00000000 r7:c07b9844 r6:00000000 r5:c07b9844 r4:c3831c10
[    2.290191] [<c0209958>] (platform_drv_probe) from [<c0207fdc>] (really_probe+0x1ac/0x26c)
[    2.298474]  r5:c080c790 r4:c3831c10
[    2.302108] [<c0207e30>] (really_probe) from [<c020813c>] (__driver_attach+0xa0/0xa4)
[    2.309883]  r8:c076704c r7:00000000 r6:c3831c44 r5:c07b9844 r4:c3831c10 r3:00000007
[    2.317666] [<c020809c>] (__driver_attach) from [<c0206408>] (bus_for_each_dev+0x6c/0x9c)
[    2.325874]  r6:c07b9844 r5:c020809c r4:00000000 r3:00000000
[    2.331524] [<c020639c>] (bus_for_each_dev) from [<c0207b00>] (driver_attach+0x20/0x28)
[    2.339558]  r6:c07b3378 r5:c3aca300 r4:c07b9844
[    2.344191] [<c0207ae0>] (driver_attach) from [<c0207780>] (bus_add_driver+0x188/0x210)
[    2.352283] [<c02075f8>] (bus_add_driver) from [<c0208830>] (driver_register+0x80/0x100)
[    2.360308]  r7:c077682c r6:c3ac1d60 r5:c0783ce0 r4:c07b9844
[    2.366016] [<c02087b0>] (driver_register) from [<c0209944>] (__platform_driver_register+0x38/0x4c)
[    2.375099]  r5:c0783ce0 r4:c0783ce0
[    2.378666] [<c020990c>] (__platform_driver_register) from [<c0767064>] (nuc980_spi0_driver_init+0x18/0x20)
[    2.388483] [<c076704c>] (nuc980_spi0_driver_init) from [<c00095a4>] (do_one_initcall+0x88/0x1ec)
[    2.397433] [<c000951c>] (do_one_initcall) from [<c0754dc4>] (kernel_init_freeable+0x108/0x1cc)
[    2.406166]  r10:000000fd r9:c0776838 r8:c077eb54 r7:c077682c r6:c07dd240 r5:c07dd240
[    2.413958]  r4:00000006
[    2.416524] [<c0754cbc>] (kernel_init_freeable) from [<c0588b0c>] (kernel_init+0x10/0xf4)
[    2.424724]  r10:00000000 r9:00000000 r8:00000000 r7:00000000 r6:00000000 r5:c0588afc
[    2.432566]  r4:00000000
[    2.435091] [<c0588afc>] (kernel_init) from [<c000fd58>] (ret_from_fork+0x14/0x3c)
[    2.442691]  r4:00000000 r3:c383e000
[    2.446283] ---[ end trace e94ecbf23b8c59cb ]---
[    2.467866] libphy: nuc980_rmii0: probed
[    2.546308] PPP generic driver version 2.4.2
[    2.553233] PPP BSD Compression module registered
[    2.557933] PPP Deflate Compression module registered
[    2.563549] PPP MPPE Compression module registered
[    2.568366] NET: Registered protocol family 24
[    2.574224] usbcore: registered new interface driver rtl8192cu
[    2.582333] usbcore: registered new interface driver ath9k_htc
[    2.589599] usbcore: registered new interface driver rtl8188fu
[    2.596483] usbcore: registered new interface driver qmi_wwan
[    2.603016] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    2.610308] nuc980-ehci b0015000.usbh_ehci: Nuvoton NUC980 EHCI Host Controller
[    2.617991] nuc980-ehci b0015000.usbh_ehci: new USB bus registered, assigned bus number 1
[    2.627016] nuc980-ehci b0015000.usbh_ehci: irq 23, io mem 0xb0015000
[    2.652141] nuc980-ehci b0015000.usbh_ehci: USB 2.0 started, EHCI 0.95
[    2.662591] hub 1-0:1.0: USB hub found
[    2.667024] hub 1-0:1.0: 2 ports detected
[    2.673174] ehci-platform: EHCI generic platform driver
[    2.679808] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    2.686316] ohci-platform: OHCI generic platform driver
[    2.693441] usbcore: registered new interface driver cdc_wdm
[    2.700766] usbcore: registered new interface driver usb-storage
[    2.708266] usbcore: registered new interface driver usbserial
[    2.715499] usbcore: registered new interface driver option
[    2.722624] usbserial: USB Serial support registered for GSM modem (1-port)
[    2.736858] i2c /dev entries driver
[    2.745408] nuc980-i2c0 b0080000.i2c0: i2c-0: nuc980 I2C adapter
[    2.757016] nuc980-i2c2 b0082000.i2c2: i2c-2: nuc980 I2C adapter
[    2.768108] nuc980_sd_probe - pdev = b0018000.sdh
[    2.819416] alg: hash: Test 1 failed for nuc980-sha1
[    2.824599] 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.830999] 00000010: 00 00 00 00
[    2.835183] alg: hash: Test 1 failed for nuc980-sha224
[    2.840299] 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.847199] 00000010: 00 00 00 00 00 00 00 00 00 00 00 00
[    2.853499] alg: hash: Test 1 failed for nuc980-sha256
[    2.858624] 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.865291] 00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.872624] alg: hash: Test 1 failed for nuc980-sha384
[    2.877749] 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.884433] 00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.890833] 00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.898133] alg: hash: Test 1 failed for nuc980-sha512
[    2.903541] 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.909949] 00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.916574] 00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.923216] 00000030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[    2.930241] alg: No test for hmac-sha1 (nuc980-hmac-sha1)
[    2.936416] alg: No test for hmac-sha224 (nuc980-hmac-sha224)
[    2.942941] alg: No test for hmac-sha256 (nuc980-hmac-sha256)
[    2.949241] alg: No test for hmac-sha384 (nuc980-hmac-sha384)
[    2.955824] alg: No test for hmac-sha512 (nuc980-hmac-sha512)
[    2.961624] NUC980 Crypto engine enabled.
[    2.984824] usbcore: registered new interface driver usbhid
[    2.990358] usbhid: USB HID core driver
[    3.006608] nand: device found, Manufacturer ID: 0xef, Chip ID: 0xaa
[    3.013341] nand: Winbond W25N01GV 1G 3.3V
[    3.017416] nand: 128 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    3.025199] nand: WARNING: spi0.0: the ECC used on your system is too weak compared to the one required by the NAND chip
[    3.036224] Scanning device for bad blocks
[    3.040533] mt29f spi0.0: read from cache failed!!
[    3.045416] Bad eraseblock 0 at 0x000000000000
[    3.050058] mt29f spi0.0: read from cache failed!!
[    3.054924] Bad eraseblock 1 at 0x000000020000
[    3.059558] mt29f spi0.0: read from cache failed!!
[    3.064433] Bad eraseblock 2 at 0x000000040000
[    3.069058] mt29f spi0.0: read from cache failed!!
[    3.073933] Bad eraseblock 3 at 0x000000060000

......此处省略n行

[   12.916599] mt29f spi0.0: read from cache failed!!
[   12.921374] Bad eraseblock 1022 at 0x000007fc0000
[   12.926358] mt29f spi0.0: read from cache failed!!
[   12.931133] Bad eraseblock 1023 at 0x000007fe0000
[   12.936883] 3 ofpart partitions found on MTD device nand0
[   12.942499] Creating 3 MTD partitions on "nand0":
[   12.947183] 0x000000000000-0x000000200000 : "u-boot"
[   12.958433] 0x000000200000-0x000000a00000 : "kernel"
[   12.970249] 0x000001600000-0x000007600000 : "rootfs"
[   13.110524] nuc980-audio ahb:sound: nau8822-hifi <-> b0020000.i2s mapping ok
[   13.229491] NET: Registered protocol family 17
[   13.235549] lib80211: common routines for IEEE802.11 drivers
[   13.275591] ALSA device list:
[   13.278524]   #0: nuc980_IIS
[   13.283699] yaffs: dev is 32505858 name is "mtdblock2" ro
[   13.289058] yaffs: passed flags "inband-tags"
[   13.294283] mt29f spi0.0: read from cache failed!!
[   13.299383] mt29f spi0.0: read from cache failed!!

......此处省略n行

[   17.238949] mt29f spi0.0: read from cache failed!!
[   17.244158] mt29f spi0.0: read from cache failed!!
[   17.273016] VFS: Mounted root (yaffs2 filesystem) readonly on device 31:2.
[   17.279933] devtmpfs: error mounting -2
[   17.285899] Freeing unused kernel memory: 176K
[   17.290566] Kernel panic - not syncing: No working init found.  Try passing init= option to kernel. See Linux Documentation/init.txt for guidance.
[   17.303666] CPU: 0 PID: 1 Comm: swapper Tainted: G        W       4.4.179 #18
[   17.310749] Hardware name: Nuvoton NUC980 (Device Tree)
[   17.315941] Backtrace: 
[   17.318449] [<c0012e2c>] (dump_backtrace) from [<c0013018>] (show_stack+0x18/0x1c)
[   17.325966]  r6:00000000 r5:c0588afc r4:c06bdacc r3:00000000
[   17.331658] [<c0013000>] (show_stack) from [<c01a769c>] (dump_stack+0x20/0x28)
[   17.338858] [<c01a767c>] (dump_stack) from [<c00785d8>] (panic+0xa4/0x234)
[   17.345699] [<c0078538>] (panic) from [<c0588bcc>] (kernel_init+0xd0/0xf4)
[   17.352508]  r3:c3840000 r2:c3f580b0 r1:60000013 r0:c06bdacc
[   17.358141]  r7:00000000
[   17.360691] [<c0588afc>] (kernel_init) from [<c000fd58>] (ret_from_fork+0x14/0x3c)
[   17.368191]  r4:00000000 r3:c383e000
[   17.371774] ---[ end Kernel panic - not syncing: No working init found.  Try passing init= option to kernel. See Linux Documentation/init.txt for guidance.
[   81.972066] random: nonblocking pool is initialized

**Comment by yachen** [comment]
Hi, 請更新附件的 dts 試試. 謝謝.
[nuc980-iot-v1.0.dts.zip](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/files/5614422/nuc980-iot-v1.0.dts.zip)

**Comment by qiubin2016** [comment]
可以正常开机了，rootfs挂载成功。但是文件系统是只读。修改bootargs=noinitrd root=/dev/mtdblock2 rw rootfstype=yaffs2 rootflags=inband-tags console=ttyS0,115200n8 rdinit=/sbin/init后，文件系统可读写。

**Comment by yachen** [comment]
等一下會把更新推出來. 謝謝.

**Comment by swapnilpanwal** [comment]
NUC980 IBR 20180813
Boot from SPI-NAND
DDR-OK
finish SPI dow�load

 SPL load main U-Boot from SPI NAND Flash! (Aug 05 2021 14:38:02)


U-Boot 2016.11 (Aug 05 2021 - 14:38:02 +0530)

CPU: NUC980
Board: NUC980
DRAM:  64 MiB
NAND:  0 MiB
SF: Detected W25N01GV with page size 2 KiB, erase size 128 KiB, total 128 MiB
In:    serial
Out:   serial
Err:   serial
Net:   Net Initialization Skipped
No ethernet found.
Hit any key to stop autoboot:  0 
SF: Detected W25N01GV with page size 2 KiB, erase size 128 KiB, total 128 MiB
device 0 offset 0x200000, size 0x800000
SF: 8388608 bytes @ 0x200000 Read: OK
device 0 offset 0x40000, size 0x10000
SF: 65536 bytes @ 0x40000 Read: OK
## Booting kernel from Legacy Image at 00007fc0 ...
   Image Name:   Linux-4.4.207
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    2675304 Bytes = 2.6 MiB
   Load Address: 00008000
   Entry Point:  00008000
   Verifying Checksum ... OK
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
=> 
**this error display**


u-boot env :
baudrate=115200
bootdelay=1
stderr=serial
stdin=serial
stdout=serial
bootargs=noinitrd root=/dev/mtdblock2 rootfstype=yaffs2 rootflags=inband-tags console=ttyS0,115200n8 rdinit=/sbin/init mem=64M
setspi=sf probe 0 30000000
loadkernel=sf read 0x7fc0 0x200000 0x800000
loaddtb=sf read 1400000 0x40000 0x10000
bootcmd=run setspi;run loadkernel;run loaddtb;bootm 0x7fc0 - 0x1400000
