### ISSUE TITLE
Missing bug fix from NUC970

### ISSUE THREAD

**Issue by parrotgeek1** [OpenNuvoton/NUC980-linux-4.4.y#45]
https://github.com/OpenNuvoton/NUC970_Linux_Kernel/commit/f6fd11eee272e6eb12892974356c11066e12b2d8 

In the future I think you should be careful to synchronize the bug fixes in all of your drivers for both chips.

**Comment by yachen** [comment]
970 and 980 use different RTC IP. 980 doesn't need this fix.

**Comment by parrotgeek1** [comment]
Sorry. The drivers are very similar, so I didn't know.

**Comment by yachen** [comment]
No problem.
