### ISSUE TITLE
Example DTS file doesn't work on NUC980-IoT

### ISSUE THREAD

**Issue by jaydcarlson** [OpenNuvoton/NUC980-linux-4.4.y#5]
When I switch to DTS-based builds (using the `nuc980-dev-v1.0.dts` file as a starting point), the kernel hangs on `Calibrating delay loop...`

I assumed it might be an RTC issue (I noticed it was disabled in the DTS file), but even after enabling it, the kernel boot-up still hangs.

Has the `nuc980-dev-v1.0.dts` file been tested on the nuc980-iot board? Should I be using a different file as a base? Thanks!

**Comment by yachen** [comment]
nuc980-dev-v1.0.dts is for DEV board. We'll proved a dts file for IoT board.

**Comment by yachen** [comment]
Hi, please pull to get dts file for IoT board. Thanks.
