### ISSUE TITLE
I2c clock speed setting

### ISSUE THREAD

**Issue by piovemas** [OpenNuvoton/NUC980-linux-4.4.y#53]
Hi,

Is it possible to change the I2c clock speed (SCL3 signal) ?
If yes, how ?

Thanks

**Comment by yachen** [comment]
Hi,

Either modify the bus_freq in arch/arm/mach-nuc980/dev.c or in nuc980.dtsi if you enabled device tree support.

**Comment by piovemas** [comment]
Hy,

I set dev.c with:
".bus_freq = 400000"

and I obtain about 330 Khz. Why this difference ? Is it possible to increase this value ?
Thanks

**Comment by yachen** [comment]
Consider the fraction being omitted, you should get a I2C clock rate slightly faster than 400k. Can you check the value been set to CLKDIV register?
```
ret = clk_get_rate(i2c->clk)/(busfreq * 4) - 1;
writel(ret & 0xffff, i2c->regs + CLKDIV);
```

**Comment by piovemas** [comment]
Hi,
ret=92
and reading CLKDIV register, I get 0x5C.

**Comment by yachen** [comment]
There's some problem with this line, it's now how the divider works is this I2C.
`ret = clk_get_rate(i2c->clk)/(busfreq * 4) - 1;`
And should be update to, that will get a 93 instead of 92.
`ret = (clk_get_rate(i2c->clk) * 10) / (busfreq * 4) + 5) / 10 - 1);`
 But ret = 92 still get a 403kHz I2C clock instead of 330kHz.

**Comment by piovemas** [comment]
Hi,
Inside NUC980_TechnicalReferenceManual_EN_Rev1.00.pdf about I2C_CLKDIV register there is:
Data Baud Rate of I2C = (system clock) / (4x (I2C_CLKDIV+1))
and inside i2c-nuc980-p3.c the inverse formula is correct.

**Comment by yachen** [comment]
Not sure what do you mean by "inverse formula is correct".
Following code can round ret to 93 which makes the output closer to target clock rate 400kHz.
`ret = (clk_get_rate(i2c->clk) * 10) / (busfreq * 4) + 5) / 10 - 1);`

**Comment by piovemas** [comment]
Hi,
also with ret = 93 I get about 330Khz on SCL. Could you verify with oscilloscope ?
