### ISSUE TITLE
NAND Flash and SD card in NUC980

### ISSUE THREAD

**Issue by tkrelcon** [OpenNuvoton/NUC980-linux-4.4.y#63]
Hey in my custom design i am Using ro RMII for Ethernet (PE and PF bus) , NAND Flash(PC bus). I also want to use SD card which is available in PC or PF port. So can use it with either NAND or Ethernet bus.  Please advise.

**Comment by yachen** [comment]
So you want to run time switch the device connect interface? I'm afraid it's not going to work unless you add switches manually cut off the signal.
