### ISSUE TITLE
How change UART2 baudrate

### ISSUE THREAD

**Issue by anton7191** [OpenNuvoton/NUC980-linux-4.4.y#68]
Hi, I turn on UART2 without DMA, but it work on baudrate=9600. And I can't find where changing this parameter. 
Would you help me please?

**Comment by yachen** [comment]
Hi, did you use cfsetospeed() and cfsetispeed() to set buadrate? Please refer to sample code in https://github.com/OpenNuvoton/NUC980_Linux_Applications/blob/master/demos/uart/uart.c

**Comment by anton7191** [comment]
I made this C code and added bin-file to my rootfs system (rootfs/sbin). But this program is not working. 
~:Illegal instruction

**Comment by yachen** [comment]
Please use file instruction on PC to check the file type.

**Comment by anton7191** [comment]
Hi, thanks for your help. I resolved this problem when I built the project with the necessary compiler.
