### ISSUE TITLE
nuc980 iot 板子 上的mac地址 出厂是不是都是一样的？

### ISSUE THREAD

**Issue by tongshi203** [OpenNuvoton/NUC980-linux-4.4.y#8]
你好：
      nuc980 iot 开发板上mac地址是不是都是一样的？
eth0      Link encap:Ethernet  HWaddr 08:00:27:00:01:92
 08:00:27:00:01:92 这个地址是哪里设置的？

**Comment by yachen** [comment]
Hi,

可以透過 u-boot 使用 ethaddr0 參數設置 EMAC0 的 MAC address.
若是沒有透過 bootarg 設置, 則都會固定使用這個 address. 這是定義在 driver 裡面.


Sincerely,

Yi-An Chen

**Comment by tongshi203** [comment]
谢谢您的回答！
