### ISSUE TITLE
能否直接通过修改makefile中的sublevel从而编译具有其它sublevel版本号的内核

### ISSUE THREAD

**Issue by TealerLinkGuo** [OpenNuvoton/NUC980-linux-4.4.y#84]

**Comment by ychuang3** [comment]
Hi,

kernel 版本需要手動打 patch 更新的。
makefile 裡面的 sublevel 只是用來做版本判定，(有些驅動或應用需要判別當前 kernel 版本是否支援)
目前 NUC980 linux kernel 的版號已進到 4.4.289 ，而目前最新的版號 4.4.299 (2022/1/11)
我們一段時間就會更新版號。
Makefile 裡面的 sublevel 需要根據實際版號去設定，所以應改為 SUBLEVEL=289，這裡我們沒有修改到。

YC
