### ISSUE TITLE
請教 NUC980 IoT yaffs2一直掛載不成功

### ISSUE THREAD

**Issue by yaojordan** [OpenNuvoton/NUC980-linux-4.4.y#89]
你好,

我想將NUC980 IoT的FS改成yaffs2,
因為不想reset之後就把資料洗掉,
根據許多教學做, 並使用NuWriter燒錄, 雖然成功開機,
但卻還是使用預設的initramfs

這是我的環境
[menuconfig.txt](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/files/8357368/menuconfig.txt)
[kernel_config.txt](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/files/8357369/kernel_config.txt)
[env.txt](https://github.com/OpenNuvoton/NUC980-linux-4.4.y/files/8357370/env.txt)

燒錄完成
<img width="543" alt="螢幕擷取畫面 2022-03-27 182503" src="https://user-images.githubusercontent.com/19225268/160277423-22602e86-c374-4762-baa1-e9ff83b71287.png">

開機之後...完全沒有任何關於yaffs的提示

> NUC980 IBR 20180813
> Boot from SPI-NAND
> DDR-OK
> finish SPI dow▒load
> 
>  SPL load main U-Boot from SPI NAND Flash! (Apr  7 2020 14:24:48)
> 
> 
> U-Boot 2016.11 (Apr 07 2020 - 14:24:11 +0800)
> 
> CPU: NUC980
> Board: NUC980
> DRAM:  64 MiB
> NAND:  NAND Flash not found !
> NUC980 NAND CONTROLLER IS NOT SUPPORT THE PAGE SIZE. (0, 0)
> 0 MiB
> SF: Detected W25N01GV with page size 2 KiB, erase size 128 KiB, total 128 MiB
> In:    serial
> Out:   serial
> Err:   serial
> Net:   Net Initialization Skipped
> No ethernet found.
> Hit any key to stop autoboot:  0
> SF: Detected W25N01GV with page size 2 KiB, erase size 128 KiB, total 128 MiB
> device 0 offset 0x200000, size 0x800000
> SF: 8388608 bytes @ 0x200000 Read: OK
>  Booting kernel from Legacy Image at 00007fc0 ...
>    Image Name:   Linux-4.4.207
>    Image Type:   ARM Linux Kernel Image (uncompressed)
>    Data Size:    5088584 Bytes = 4.9 MiB
>    Load Address: 00008000
>    Entry Point:  00008000
>    Verifying Checksum ... OK
>    XIP Kernel Image ... OK
> 
> Starting kernel ...
> 
> SF: Detected W25N01GV with page size 2 KiB, erase size 128 KiB, total 128 MiB
> SF: DeviceBooting Linux on physical CPU 0x0
> Linux version 4.4.207 (user@ubuntu) (gcc version 4.8.5 (Buildroot 2016.11.1-g66ba911) ) #6 PREEMPT Sun Mar 27 17:56:12 CST 2022
> CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=0005317f
> CPU: VIVT data cache, VIVT instruction cache
> Machine: NUC980
> Memory policy: Data cache writeback
> Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16256
> Kernel command line: noinitrd root=/dev/mtdblock2 rootfstype=yaffs2 rootflags=inband-tags console=ttyS0,115200n8 rdinit=/sbin/init mem=64M mtdparts=nand0:0x200000@0(u-boot),0x1400000@0x200000(kernel),-(user)ignore_loglevel
> PID hash table entries: 256 (order: -2, 1024 bytes)
> Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
> Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
> Memory: 56708K/65536K available (4034K kernel code, 288K rwdata, 1252K rodata, 2376K init, 219K bss, 8828K reserved, 0K cma-reserved)
> Virtual kernel memory layout:
>     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
>     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
>     vmalloc : 0xc4800000 - 0xff800000   ( 944 MB)
>     lowmem  : 0xc0000000 - 0xc4000000   (  64 MB)
>     modules : 0xbf000000 - 0xc0000000   (  16 MB)
>       .text : 0xc0008000 - 0xc0531e24   (5288 kB)
>       .init : 0xc0532000 - 0xc0784000   (2376 kB)
>       .data : 0xc0784000 - 0xc07cc120   ( 289 kB)
>        .bss : 0xc07cc120 - 0xc0802e90   ( 220 kB)
> SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
> Preemptible hierarchical RCU implementation.
>         Build-time adjustment of leaf fanout to 32.
> NR_IRQS:545
> clocksource: nuc980-timer5: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 62215505635 ns
> sched_clock: 24 bits at 120kHz, resolution 8333ns, wraps every 69905062489ns
> Console: colour dummy device 80x30
> console [ttyS0] enabled
> Calibrating delay loop... 148.88 BogoMIPS (lpj=744448)
> pid_max: default: 32768 minimum: 301
> Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
> Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
> CPU: Testing write buffer coherency: ok
> Setting up static identity map for 0x8400 - 0x843c
> devtmpfs: initialized
> clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
> futex hash table entries: 256 (order: -1, 3072 bytes)
> pinctrl core: initialized pinctrl subsystem
> NET: Registered protocol family 16
> DMA: preallocated 256 KiB pool for atomic coherent allocations
> SCSI subsystem initialized
> usbcore: registered new interface driver usbfs
> usbcore: registered new interface driver hub
> usbcore: registered new device driver usb
> Advanced Linux Sound Architecture Driver Initialized.
> clocksource: Switched to clocksource nuc980-timer5
> NET: Registered protocol family 2
> TCP established hash table entries: 1024 (order: 0, 4096 bytes)
> TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
> TCP: Hash tables configured (established 1024 bind 1024)
> UDP hash table entries: 256 (order: 0, 4096 bytes)
> UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
> NET: Registered protocol family 1
> NetWinder Floating Point Emulator V0.97 (double precision)
> Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
> io scheduler noop registered (default)
> nuc980_gpio_probe - pdev = nuc980-gpio
> nuc980_dma_probe - pdev = nuc980-dma
> nuc980-dma nuc980-dma: NUC980 DMA ready
> nuc980-uart.0: ttyS0 at I/O 0x0 (irq = 36, base_baud = 750000) is a NUC980
> nuc980-uart.1: ttyS1 at I/O 0x0 (irq = 37, base_baud = 9375000) is a NUC980
> nuc980-uart.2: ttyS2 at I/O 0x0 (irq = 38, base_baud = 9375000) is a NUC980
> nuvoton-rng nuvoton-rng: nuvoton PRNG active
> brd: module loaded
> RX nuc980_qspi0_probe: dma0chan0 module removed
> TX nuc980_qspi0_probe: dma0chan1 module removed
> RX nuc980_spi0_probe: dma0chan2 module removed
> TX nuc980_spi0_probe: dma0chan3 module removed
> m25p80 spi1.1: unrecognized JEDEC id bytes: ff, ff, ff
> m25p80: probe of spi1.1 failed with error -2
> libphy: nuc980_rmii0: probed
> PPP generic driver version 2.4.2
> PPP BSD Compression module registered
> PPP Deflate Compression module registered
> PPP MPPE Compression module registered
> NET: Registered protocol family 24
> usbcore: registered new interface driver qmi_wwan
> ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
> nuc980-ehci nuc980-ehci: Nuvoton NUC980 EHCI Host Controller
> nuc980-ehci nuc980-ehci: new USB bus registered, assigned bus number 1
> nuc980-ehci nuc980-ehci: irq 23, io mem 0xb0015000
> nuc980-ehci nuc980-ehci: USB 2.0 started, EHCI 0.95
> hub 1-0:1.0: USB hub found
> hub 1-0:1.0: 2 ports detected
> ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
> usb_hcd_nuc980_probe, id = 0, name: nuc980-ohci.0, 0
> nuc980-ohci nuc980-ohci.0: Nuvoton NUC980 OHCI Host Controller
> nuc980-ohci nuc980-ohci.0: new USB bus registered, assigned bus number 2
> nuc980-ohci nuc980-ohci.0: irq 24, io mem 0xb0017000
> hub 2-0:1.0: USB hub found
> hub 2-0:1.0: 8 ports detected
> usb_hcd_nuc980_probe, id = 1, name: nuc980-ohci.1, 0
> usb_hcd_nuc980_probe, id = 2, name: nuc980-ohci.2, 0
> usb_hcd_nuc980_probe, id = 3, name: nuc980-ohci.3, 0
> usb_hcd_nuc980_probe, id = 4, name: nuc980-ohci.4, 0
> usb_hcd_nuc980_probe, id = 5, name: nuc980-ohci.5, 0
> usb_hcd_nuc980_probe, id = 6, name: nuc980-ohci.6, 0
> usbcore: registered new interface driver cdc_wdm
> usbcore: registered new interface driver usb-storage
> usbcore: registered new interface driver usbserial
> usbcore: registered new interface driver option
> usbserial: USB Serial support registered for GSM modem (1-port)
> nuc980-i2c0 nuc980-i2c0: i2c-0: nuc980 I2C adapter
> nuc980-i2c2 nuc980-i2c2: i2c-2: nuc980 I2C adapter
> nuc980_sd_probe - pdev = nuc980-sdh
> do_sha - sha last has no data!
> alg: hash: Test 1 failed for nuc980-sha1
> 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 00000010: 00 00 00 00
> do_sha - sha last has no data!
> alg: hash: Test 1 failed for nuc980-sha224
> 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 00000010: 00 00 00 00 00 00 00 00 00 00 00 00
> do_sha - sha last has no data!
> alg: hash: Test 1 failed for nuc980-sha256
> 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> do_sha - sha last has no data!
> alg: hash: Test 1 failed for nuc980-sha384
> 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> do_sha - sha last has no data!
> alg: hash: Test 1 failed for nuc980-sha512
> 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 00000030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> alg: No test for hmac-sha1 (nuc980-hmac-sha1)
> alg: No test for hmac-sha224 (nuc980-hmac-sha224)
> alg: No test for hmac-sha256 (nuc980-hmac-sha256)
> alg: No test for hmac-sha384 (nuc980-hmac-sha384)
> alg: No test for hmac-sha512 (nuc980-hmac-sha512)
> NUC980 Crypto engine enabled.
> usbcore: registered new interface driver usbhid
> usbhid: USB HID core driver
> nand: device found, Manufacturer ID: 0xef, Chip ID: 0xaa
> nand: Winbond W25N01GV 1G 3.3V
> nand: 128 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
> nand: WARNING: spi0.0: the ECC used on your system is too weak compared to the one required by the NAND chip
> Scanning device for bad blocks
> Creating 3 MTD partitions on "nand0":
> 0x000000000000-0x000000200000 : "u-boot"
> 0x000000200000-0x000001600000 : "Kernel"
> 0x000001600000-0x000008000000 : "user"
> nuc980-nadc: nuc980 Normal ADC adapter
> nuc980-audio nuc980-audio: nau8822-hifi <-> nuc980-audio-i2s mapping ok
> NET: Registered protocol family 10
> sit: IPv6 over IPv4 tunneling driver
> NET: Registered protocol family 17
> lib80211: common routines for IEEE802.11 drivers
> ALSA device list:
>   #0: nuc980_IIS
> Freeing unused kernel memory: 2376K
> Starting logging: OK
> Starting mdev...
> Initializing random number generator... random: dd: uninitialized urandom read (512 bytes read, 16 bits of entropy available)
> done.
> Starting network: OK

進到系統後, partition也確實有切出來

> cat /proc/mtd
> dev:    size   erasesize  name
> mtd0: 00200000 00020000 "u-boot"
> mtd1: 01400000 00020000 "Kernel"
> mtd2: 06a00000 00020000 "user"

我用手動mount是沒問題的, 但reset後還是會全部不見
mount -t yaffs2 -o "inband-tags" /dev/mtdblock2 /mnt

另外, 我編譯的時候並沒有取消勾選
linux-menuconfig->General Setup->Initial RAM filesystem Support...

否則系統開機會直接死在這邊, 連mtd都沒掛上

> ALSA device list:
>   No soundcards found.
> VFS: Cannot open root device "mtdblock2" or unknown-block(0,0): error -6
> Please append a correct "root=" boot option; here are the available partitions:
> 0100           16384 ram0  (driver?)
> 0101           16384 ram1  (driver?)
> 0102           16384 ram2  (driver?)
> 0103           16384 ram3  (driver?)
> 0104           16384 ram4  (driver?)
> 0105           16384 ram5  (driver?)
> 0106           16384 ram6  (driver?)
> 0107           16384 ram7  (driver?)
> 0108           16384 ram8  (driver?)
> 0109           16384 ram9  (driver?)
> 010a           16384 ram10  (driver?)
> 010b           16384 ram11  (driver?)
> 010c           16384 ram12  (driver?)
> 010d           16384 ram13  (driver?)
> 010e           16384 ram14  (driver?)
> 010f           16384 ram15  (driver?)
> Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
> CPU: 0 PID: 1 Comm: swapper Not tainted 4.4.207 #9
> Hardware name: NUC980
> Backtrace:
> [<c0012e40>] (dump_backtrace) from [<c001302c>] (show_stack+0x18/0x1c)
>  r6:c3b03000 r5:c3b03000 r4:c04d2cdc r3:00000000
> [<c0013014>] (show_stack) from [<c017e298>] (dump_stack+0x20/0x28)
> [<c017e278>] (dump_stack) from [<c0075f28>] (panic+0xb0/0x240)
> [<c0075e7c>] (panic) from [<c054820c>] (mount_block_root+0x224/0x2d8)
>  r3:00000001 r2:00000000 r1:c383fec0 r0:c04d2cdc
>  r7:c3fed060
> [<c0547fe8>] (mount_block_root) from [<c0548424>] (mount_root+0x68/0x84)
>  r10:0000007a r9:c0568838 r8:c056ebd4 r7:c0568830 r6:c0568858 r5:c0568858
>  r4:00000000
> [<c05483bc>] (mount_root) from [<c05485a0>] (prepare_namespace+0x160/0x1c0)
>  r4:c05b8264 r3:00000000
> [<c0548440>] (prepare_namespace) from [<c0547e34>] (kernel_init_freeable+0x184/0x1cc)
>  r6:c05b8240 r5:c05b8240 r4:00000007
> [<c0547cb0>] (kernel_init_freeable) from [<c03ff12c>] (kernel_init+0x10/0xf4)
>  r10:00000000 r9:00000000 r8:00000000 r7:00000000 r6:00000000 r5:c03ff11c
>  r4:00000000
> [<c03ff11c>] (kernel_init) from [<c000fd78>] (ret_from_fork+0x14/0x3c)
>  r4:00000000 r3:ffffffff
> ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
> random: nonblocking pool is initialized

覺得很怪...參數應該都有設定
bootargs也有吃到
請幫忙看看
萬分感謝

**Comment by ychuang3** [comment]
"NUC980 Linux 4.4 BSP User Manual EN"  文件裡面有說明

**Comment by yaojordan** [comment]
Dear ychuang,

折騰了半天原來是kernel config沒開FMI(Flash Memory Interface)...
做以下設定後即可:
```
Device Drivers ---> 
    Generic Driver Options --->
        <*> Nuvoton NUC980 FMI function selection
            Select FMI device to support (Support MTD NAND Flash) --->
```
接著將Initial RAM filesystem disabled, 板子reset後便能掛上YAFFS2
```
General setup --->
    [ ] Initial RAM filesystem and RAM disk (initramfs/initrd) support
```

資料查了半天都沒想到去讀官方文件, 非常感謝您一針見血的提點
