### ISSUE TITLE
内核编译出现“recipe for target 'usr/initramfs_data.cpio.gz' failed”

### ISSUE THREAD

**Issue by M16AK47MMM** [OpenNuvoton/NUC980-linux-4.4.y#99]
新下载4.4.289内核源码进行编译出现“recipe for target 'usr/initramfs_data.cpio.gz' failed”错误，在配置方面有哪些需要注意的吗？

**Comment by ychuang3** [comment]
此版本已經 release 數月，沒有收到 build 問題，請整個清除重編看看
make clean
make nuc980_defconfig
make menuconfig
make

**Comment by M16AK47MMM** [comment]
按文档编译还是会出现以下报错，不知有哪些细节需要特别注意；
![01](https://user-images.githubusercontent.com/106132460/170170823-b182ecbd-013a-4eb0-951c-07e3bec75ce5.png)

**Comment by ychuang3** [comment]
你這是單獨 compile kernel，缺少 rootfs，不建議這麼做
請用 buildroot

**Comment by ychuang3** [comment]
download https://github.com/OpenNuvoton/NUC970_Buildroot

make nuvoton_nuc980_defconfig
make

**Comment by M16AK47MMM** [comment]
请问下有NUC980内核具体编译步骤吗？我按照官方提供的Linux_BSP执导手册进行编译会报错。

**Comment by ychuang3** [comment]
用 buildroot 就可以了，包含 kernel 全部都會編好
